/**
 * Сводный отчёт массового разбора — один самодостаточный HTML-файл:
 * все договоры пачки, отсортированные по риску, с топ-находками каждого.
 * Это «дью-дилидженс дельиверабл»: то, что юрист кладёт клиенту на стол.
 * Стиль и подход — как у lib/exportHtml.ts (всё экранируется, без внешних
 * ресурсов, печатается в PDF средствами браузера).
 * Рамка отчёта — на языке КОНТЕНТА (по находкам разобранных договоров),
 * как у PDF-отчёта анализа: файл уходит третьим лицам, а не живёт в UI.
 */
import { looksRussian, looksUzbekCyrillic, looksUzbekLatin } from './format.ts';

function esc(v: unknown): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export interface BatchReportItem {
  fileName: string;
  status: string;
  riskScore: number | null;
  riskLevel: string | null;
  findingsCount: number | null;
  error: string | null;
  topFindings: { severity: string; title: string; citation: string; verified: boolean }[];
}

export interface BatchReportData {
  jobId: string;
  createdAt: string;
  jurisdiction: string | null;
  ownerName: string;
  ownerFirm: string;
  items: BatchReportItem[];
}

const LEVEL_COLOR: Record<string, string> = { High: '#c0392b', Elevated: '#b9770e', Low: '#1e8449' };

interface Frame {
  htmlLang: string;
  dateLocale: string;
  title: string;
  h1: string;
  job: string;
  tiles: { done: string; high: string; avg: string; findings: string };
  th: { doc: string; score: string; risk: string; findings: string };
  level: Record<string, string>;
  sev: Record<string, string>;
  foot: string;
}

const FRAMES: Record<'ru' | 'uz' | 'uzc' | 'en', Frame> = {
  ru: {
    htmlLang: 'ru',
    dateLocale: 'ru-RU',
    title: 'Lexab — сводный отчёт разбора',
    h1: 'Сводный отчёт массового разбора',
    job: 'задание',
    tiles: { done: 'договоров разобрано', high: 'с высоким риском', avg: 'средний балл риска', findings: 'находок всего' },
    th: { doc: 'Договор и ключевые находки', score: 'Балл', risk: 'Риск', findings: 'Находки' },
    level: { High: 'Высокий', Elevated: 'Повышенный', Low: 'Низкий' },
    sev: { High: 'Высокая', Medium: 'Средняя', Low: 'Низкая' },
    foot: 'Сформировано в Lexab. Цитаты с отметкой ✓ подтверждены по базе официальных источников законодательства. Отчёт носит информационный характер и не является юридическим заключением.',
  },
  uz: {
    htmlLang: 'uz',
    dateLocale: 'uz',
    title: 'Lexab — ommaviy tahlil yakuniy hisoboti',
    h1: 'Ommaviy tahlil yakuniy hisoboti',
    job: 'topshiriq',
    tiles: { done: 'shartnoma tahlil qilindi', high: 'yuqori xavfli', avg: "o'rtacha xavf bahosi", findings: 'jami topilmalar' },
    th: { doc: 'Shartnoma va asosiy topilmalar', score: 'Ball', risk: 'Xavf', findings: 'Topilmalar' },
    level: { High: 'Yuqori', Elevated: "Ko'tarilgan", Low: 'Past' },
    sev: { High: 'Yuqori', Medium: "O'rta", Low: 'Past' },
    foot: "Lexab tomonidan shakllantirilgan. ✓ belgili iqtiboslar rasmiy qonunchilik manbalari bazasi bo'yicha tasdiqlangan. Hisobot axborot xarakteriga ega va yuridik xulosa hisoblanmaydi.",
  },
  uzc: {
    htmlLang: 'uz',
    dateLocale: 'uz-Cyrl',
    title: 'Lexab — оммавий таҳлил якуний ҳисоботи',
    h1: 'Оммавий таҳлил якуний ҳисоботи',
    job: 'топшириқ',
    tiles: { done: 'шартнома таҳлил қилинди', high: 'юқори хавфли', avg: 'ўртача хавф баҳоси', findings: 'жами топилмалар' },
    th: { doc: 'Шартнома ва асосий топилмалар', score: 'Балл', risk: 'Хавф', findings: 'Топилмалар' },
    level: { High: 'Юқори', Elevated: 'Кўтарилган', Low: 'Паст' },
    sev: { High: 'Юқори', Medium: 'Ўрта', Low: 'Паст' },
    foot: 'Lexab томонидан шакллантирилган. ✓ белгили иқтибослар расмий қонунчилик манбалари базаси бўйича тасдиқланган. Ҳисобот ахборот характерига эга ва юридик хулоса ҳисобланмайди.',
  },
  en: {
    htmlLang: 'en',
    dateLocale: 'en-GB',
    title: 'Lexab — Batch Review Summary Report',
    h1: 'Batch Review Summary Report',
    job: 'job',
    tiles: { done: 'contracts reviewed', high: 'high risk', avg: 'average risk score', findings: 'total findings' },
    th: { doc: 'Contract and key findings', score: 'Score', risk: 'Risk', findings: 'Findings' },
    level: { High: 'High', Elevated: 'Elevated', Low: 'Low' },
    sev: { High: 'High', Medium: 'Medium', Low: 'Low' },
    foot: 'Generated by Lexab. Citations marked ✓ are verified against the corpus of official legislation sources. This report is informational and does not constitute a legal opinion.',
  },
};

/** Язык рамки — по тексту находок (контент ИИ на языке договоров пачки). */
function detectFrame(items: BatchReportItem[]): Frame {
  const sample = items
    .flatMap((i) => i.topFindings.map((f) => f.title))
    .join(' ')
    .slice(0, 4000);
  if (looksUzbekLatin(sample)) return FRAMES.uz;
  if (looksUzbekCyrillic(sample)) return FRAMES.uzc;
  if (looksRussian(sample)) return FRAMES.ru;
  return FRAMES.en;
}

export function renderBatchReportHtml(data: BatchReportData): string {
  const F = detectFrame(data.items);
  const done = data.items.filter((i) => i.status === 'done' && i.riskScore !== null);
  const failed = data.items.filter((i) => i.status !== 'done');
  const sorted = [...done].sort((a, b) => (b.riskScore ?? 0) - (a.riskScore ?? 0));
  const avg = done.length ? Math.round(done.reduce((s, i) => s + (i.riskScore ?? 0), 0) / done.length) : 0;
  const high = done.filter((i) => i.riskLevel === 'High').length;
  const findingsTotal = done.reduce((s, i) => s + (i.findingsCount ?? 0), 0);

  const rows = sorted
    .map((i, idx) => {
      const tone = LEVEL_COLOR[i.riskLevel ?? ''] ?? '#555';
      const tf = i.topFindings
        .map(
          (f) =>
            `<li><span class="sev" style="color:${LEVEL_COLOR[f.severity === 'Medium' ? 'Elevated' : f.severity] ?? '#555'}">${esc(F.sev[f.severity] ?? f.severity)}</span> ${esc(f.title)} <span class="cite">${esc(f.citation)}${f.verified ? ' ✓' : ''}</span></li>`,
        )
        .join('');
      return `<tr>
        <td class="num">${idx + 1}</td>
        <td><strong>${esc(i.fileName)}</strong>${tf ? `<ul class="tf">${tf}</ul>` : ''}</td>
        <td class="score" style="color:${tone}">${i.riskScore}</td>
        <td style="color:${tone}">${esc(F.level[i.riskLevel ?? ''] ?? i.riskLevel ?? '—')}</td>
        <td class="num">${i.findingsCount ?? 0}</td>
      </tr>`;
    })
    .join('');

  const failedRows = failed
    .map((i) => `<tr><td colspan="2"><strong>${esc(i.fileName)}</strong></td><td colspan="3" class="err">${esc(i.error ?? i.status)}</td></tr>`)
    .join('');

  return `<!doctype html>
<html lang="${F.htmlLang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(F.title)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; margin: 0; background: #f6f6f8; color: #16181d; }
  .wrap { max-width: 900px; margin: 0 auto; padding: 40px 24px 64px; }
  h1 { font-size: 24px; margin: 0 0 4px; }
  .sub { color: #6b7078; margin: 0 0 24px; font-size: 14px; }
  .tiles { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 28px; }
  .tile { background: #fff; border: 1px solid #e3e5ea; border-radius: 12px; padding: 14px 20px; min-width: 140px; }
  .tile b { display: block; font-size: 22px; }
  .tile span { color: #6b7078; font-size: 12.5px; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e3e5ea; border-radius: 12px; overflow: hidden; }
  th { text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7078; padding: 10px 12px; border-bottom: 1px solid #e3e5ea; }
  td { padding: 12px; border-bottom: 1px solid #eef0f3; vertical-align: top; font-size: 14px; }
  td.num, td.score { text-align: center; white-space: nowrap; }
  td.score { font-weight: 700; font-size: 16px; }
  ul.tf { margin: 8px 0 0; padding-inline-start: 18px; color: #40454d; font-size: 13px; }
  ul.tf li { margin-bottom: 3px; }
  .sev { font-weight: 600; }
  .cite { color: #6b7078; font-family: ui-monospace, monospace; font-size: 12px; }
  .err { color: #c0392b; font-size: 13px; }
  .foot { margin-top: 28px; color: #8a8f98; font-size: 12.5px; }
  @media print { body { background: #fff; } .wrap { padding: 0; } }
</style>
</head>
<body>
<div class="wrap">
  <h1>${esc(F.h1)}</h1>
  <p class="sub">${esc(data.ownerFirm)} · ${esc(data.ownerName)} · ${esc(new Date(data.createdAt).toLocaleDateString(F.dateLocale))}${data.jurisdiction ? ` · ${esc(data.jurisdiction)}` : ''} · ${esc(F.job)} ${esc(data.jobId)}</p>
  <div class="tiles">
    <div class="tile"><b>${done.length}</b><span>${esc(F.tiles.done)}</span></div>
    <div class="tile"><b style="color:${high ? '#c0392b' : '#1e8449'}">${high}</b><span>${esc(F.tiles.high)}</span></div>
    <div class="tile"><b>${avg}</b><span>${esc(F.tiles.avg)}</span></div>
    <div class="tile"><b>${findingsTotal}</b><span>${esc(F.tiles.findings)}</span></div>
  </div>
  <table>
    <thead><tr><th>#</th><th>${esc(F.th.doc)}</th><th>${esc(F.th.score)}</th><th>${esc(F.th.risk)}</th><th>${esc(F.th.findings)}</th></tr></thead>
    <tbody>${rows}${failedRows}</tbody>
  </table>
  <p class="foot">${esc(F.foot)}</p>
</div>
</body>
</html>`;
}
