import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Avatar } from '@/components/ui/Avatar';
import { useI18n } from '@/i18n/I18nProvider';
import { pickText } from '@/i18n/messages';
import { usePageTitle } from '@/hooks/usePageTitle';
import styles from './pages.module.css';

interface Section {
  id: string;
  h: { ru: string; en: string };
  p: { ru: string; en: string }[];
}

const TERMS: Section[] = [
  {
    id: 'definitions',
    h: { ru: '1. Определения', en: '1. Definitions' },
    p: [
      {
        ru: '«Сервис» — платформа Lexab, доступная через веб-приложение, включая анализ документов, чат с ИИ-ассистентом, шаблоны, электронные подписи и связанные функции. «Мы», «Lexab» — оператор сервиса. «Пользователь», «вы» — лицо, создавшее аккаунт или использующее сервис. «Контент пользователя» — документы, тексты и иные материалы, которые вы загружаете в сервис. «Тариф» — выбранный вами план подписки, определяющий объём доступных функций.',
        en: '“Service” means the Lexab platform available through the web application, including document analysis, the AI assistant chat, templates, e-signatures and related features. “We” and “Lexab” mean the service operator. “User” and “you” mean the person who created an account or uses the service. “User content” means documents, texts and other materials you upload to the service. “Plan” means the subscription plan you selected, which defines the scope of available features.',
      },
    ],
  },
  {
    id: 'service',
    h: { ru: '2. Описание сервиса', en: '2. Service description' },
    p: [
      {
        ru: 'Lexab — платформа интеллектуального анализа договоров: загрузка документов, автоматический поиск рисков с привязкой к законодательству, правки, шаблоны, чат с ИИ-ассистентом и электронные подписи.',
        en: 'Lexab is an AI contract-intelligence platform: document upload, automated risk review linked to legislation, redlines, templates, an AI assistant chat and e-signatures.',
      },
      {
        ru: 'Анализ выполняют большие языковые модели. Находки, ссылающиеся на правовые нормы, сопоставляются с базой официальных текстов законов, а цитаты проходят автоматическую проверку: ссылка без подтверждённого источника помечается как непроверенная.',
        en: 'Analysis is performed by large language models. Findings that reference legal provisions are matched against a corpus of official statutory texts, and citations are automatically validated: a reference without a confirmed source is flagged as unverified.',
      },
    ],
  },
  {
    id: 'not-legal-advice',
    h: { ru: '3. Не является юридической консультацией', en: '3. Not legal advice' },
    p: [
      {
        ru: 'Результаты работы сервиса формируются искусственным интеллектом и носят исключительно информационный и вспомогательный характер. Они не являются юридической консультацией и не создают отношений «юрист — клиент».',
        en: 'The output of the service is generated by artificial intelligence and is informational and supportive in nature only. It does not constitute legal advice and does not create a lawyer–client relationship.',
      },
      {
        ru: 'ИИ может ошибаться: пропускать риски, неточно толковать нормы или неверно оценивать серьёзность условий. Любые результаты анализа должны проверяться квалифицированным юристом до того, как на их основе будут приниматься решения.',
        en: 'AI can make mistakes: it may miss risks, misinterpret legal provisions or misjudge the severity of contract terms. Any analysis output must be reviewed by a qualified lawyer before decisions are made on its basis.',
      },
      {
        ru: 'Ответственность за принятые решения — подписание договора, отказ от сделки, направление претензии и тому подобное — несёт пользователь или его юрист. Lexab — вспомогательный инструмент, а не замена профессионального суждения.',
        en: 'Responsibility for decisions taken — signing a contract, walking away from a deal, sending a claim and the like — rests with the user or their lawyer. Lexab is a supporting tool, not a substitute for professional judgement.',
      },
    ],
  },
  {
    id: 'account',
    h: { ru: '4. Аккаунт и безопасность', en: '4. Account and security' },
    p: [
      {
        ru: 'Для использования сервиса нужен аккаунт: регистрация по email и паролю либо вход через Google. Вы обязуетесь указывать достоверные данные и поддерживать их актуальность.',
        en: 'Using the service requires an account: registration with email and password, or sign-in with Google. You agree to provide accurate information and keep it up to date.',
      },
      {
        ru: 'Вы отвечаете за сохранность своих учётных данных и за все действия, совершённые из-под вашего аккаунта. При подозрении на несанкционированный доступ смените пароль и сообщите нам через контакты в разделе «Контакты».',
        en: 'You are responsible for keeping your credentials safe and for all activity under your account. If you suspect unauthorised access, change your password and notify us via the details in the “Contact” section.',
      },
    ],
  },
  {
    id: 'plans',
    h: { ru: '5. Тарифы и оплата', en: '5. Plans and payment' },
    p: [
      {
        ru: 'Сервис предлагает четыре тарифа: Free, Standard, Pro и Business. Объём доступных функций (ИИ-запросы, документы, хранилище, участники команды) определяется выбранным тарифом; актуальные лимиты указаны на странице «Тарифы» и в Настройках.',
        en: 'The service offers four plans: Free, Standard, Pro and Business. Available usage (AI requests, documents, storage, team seats) is defined by your plan; current limits are shown on the Plans page and in Settings.',
      },
      {
        ru: 'Тариф Free предоставляется без привязки банковской карты. Платные тарифы оплачиваются помесячно или за год вперёд; при годовой оплате действует скидка 15%.',
        en: 'The Free plan is available without adding a payment card. Paid plans are billed monthly or annually; annual billing comes with a 15% discount.',
      },
      {
        ru: 'Мы можем изменять состав и стоимость тарифов. Изменения не применяются задним числом к уже оплаченному периоду.',
        en: 'We may change the contents and pricing of plans. Changes do not apply retroactively to a period you have already paid for.',
      },
      {
        ru: 'Оформляя платный тариф, вы просите начать оказание услуги немедленно и прямо подтверждаете, что после начала предоставления услуги теряете право на 14-дневный отказ (возврат), предусмотренное правилами дистанционных договоров ЕС/Великобритании. Оплата за начатый расчётный период не возвращается. При отмене подписки доступ сохраняется до конца оплаченного периода, после чего аккаунт переводится на тариф Free. Ваши обязательные права потребителя по применимому законодательству это положение не затрагивает.',
        en: 'By purchasing a paid plan you request that the service begin immediately and expressly acknowledge that, once performance has started, you lose the 14-day right of withdrawal (refund) under EU/UK distance-selling rules. Payment for a started billing period is non-refundable. On cancellation, access continues until the end of the paid period, after which the account moves to the Free plan. This does not affect your mandatory statutory consumer rights under applicable law.',
      },
    ],
  },
  {
    id: 'acceptable-use',
    h: { ru: '6. Допустимое использование', en: '6. Acceptable use' },
    p: [
      {
        ru: 'Запрещено использовать сервис для незаконных целей, нарушения прав третьих лиц, загрузки вредоносного кода, а также для попыток получить несанкционированный доступ к сервису или данным других пользователей.',
        en: 'You may not use the service for unlawful purposes, to infringe third-party rights, to upload malicious code, or to attempt unauthorised access to the service or other users’ data.',
      },
      {
        ru: 'Также запрещены автоматизированный сбор данных сервиса, обход лимитов тарифа, перепродажа доступа без нашего согласия и действия, создающие несоразмерную нагрузку на инфраструктуру. При злоупотреблениях мы можем ограничить или приостановить доступ к аккаунту.',
        en: 'Automated scraping of the service, circumventing plan limits, reselling access without our consent, and activity that places disproportionate load on the infrastructure are also prohibited. In case of abuse we may restrict or suspend access to the account.',
      },
    ],
  },
  {
    id: 'ip',
    h: { ru: '7. Интеллектуальная собственность', en: '7. Intellectual property' },
    p: [
      {
        ru: 'Загруженные вами документы и материалы остаются вашей собственностью. Вы предоставляете Lexab ограниченную лицензию на их обработку исключительно для оказания услуг: хранение, извлечение текста, анализ и отображение результатов в вашем кабинете. Эта лицензия прекращается при удалении документа или аккаунта.',
        en: 'Documents and materials you upload remain your property. You grant Lexab a limited licence to process them solely to provide the service: storage, text extraction, analysis and displaying results in your workspace. This licence ends when the document or the account is deleted.',
      },
      {
        ru: 'Сервис, его код, интерфейс, товарные обозначения и база правовых текстов с аннотациями принадлежат Lexab или используются на законных основаниях. Настоящие условия не передают вам никаких прав на сервис, кроме права пользования в рамках выбранного тарифа.',
        en: 'The service, its code, interface, trade marks and the annotated corpus of legal texts belong to Lexab or are used under lawful grounds. These terms grant you no rights in the service other than the right to use it under your chosen plan.',
      },
    ],
  },
  {
    id: 'teams',
    h: { ru: '8. Команды и роли (Business)', en: '8. Teams and roles (Business)' },
    p: [
      {
        ru: 'На тарифе Business владелец аккаунта может приглашать участников в команду и назначать им роли. Владелец управляет подпиской и составом команды и отвечает за действия приглашённых участников.',
        en: 'On the Business plan the account owner can invite members to a team and assign them roles. The owner manages the subscription and team membership and is responsible for the actions of invited members.',
      },
      {
        ru: 'Документы и результаты анализа, открытые для команды, видны её участникам в соответствии с настройками доступа. Приглашая участника, убедитесь, что вы вправе предоставить ему такой доступ.',
        en: 'Documents and analyses shared with the team are visible to its members according to access settings. Before inviting a member, make sure you are entitled to grant them that access.',
      },
    ],
  },
  {
    id: 'availability',
    h: { ru: '9. Доступность сервиса и бета-функции', en: '9. Availability and beta features' },
    p: [
      {
        ru: 'Сервис предоставляется «как есть» и «как доступно». Мы стремимся к стабильной работе, но не гарантируем бесперебойность и отсутствие ошибок и не предоставляем гарантий уровня обслуживания (SLA).',
        en: 'The service is provided “as is” and “as available”. We aim for stable operation but do not guarantee uninterrupted or error-free service and do not provide service-level (SLA) guarantees.',
      },
      {
        ru: 'Отдельные функции могут быть помечены как бета-версии: они предоставляются для ознакомления и могут изменяться или отключаться без предварительного уведомления.',
        en: 'Certain features may be marked as beta: they are offered for evaluation and may change or be discontinued without prior notice.',
      },
    ],
  },
  {
    id: 'liability',
    h: { ru: '10. Ограничение ответственности', en: '10. Limitation of liability' },
    p: [
      {
        ru: 'В максимальной степени, допустимой применимым правом, Lexab не отвечает за косвенные убытки, упущенную выгоду, потерю данных или деловой репутации, возникшие в связи с использованием сервиса или невозможностью его использования.',
        en: 'To the maximum extent permitted by applicable law, Lexab is not liable for indirect losses, lost profits, loss of data or goodwill arising from the use of, or inability to use, the service.',
      },
      {
        ru: 'Совокупная ответственность Lexab по любым требованиям ограничена суммой, уплаченной вами за сервис за 12 месяцев, предшествующих событию, из которого возникло требование. Ничто в этих условиях не ограничивает ответственность, которая не может быть ограничена по закону.',
        en: 'Lexab’s aggregate liability for any claims is limited to the amount you paid for the service in the 12 months preceding the event giving rise to the claim. Nothing in these terms limits liability that cannot be limited by law.',
      },
    ],
  },
  {
    id: 'termination',
    h: { ru: '11. Прекращение и удаление аккаунта', en: '11. Termination and account deletion' },
    p: [
      {
        ru: 'Вы можете прекратить использование сервиса в любой момент и удалить аккаунт самостоятельно (Настройки → Безопасность → Удалить аккаунт). При удалении аккаунта удаляются записи в базе данных и файлы из хранилища; удаление необратимо.',
        en: 'You may stop using the service at any time and delete your account yourself (Settings → Security → Delete account). Deleting the account removes database records and files from storage; deletion is irreversible.',
      },
      {
        ru: 'Мы можем приостановить или прекратить доступ при существенном нарушении настоящих условий, уведомив вас, когда это возможно. Положения об интеллектуальной собственности и ограничении ответственности сохраняют силу после прекращения доступа.',
        en: 'We may suspend or terminate access in case of a material breach of these terms, notifying you where possible. The intellectual-property and limitation-of-liability provisions survive termination.',
      },
    ],
  },
  {
    id: 'changes',
    h: { ru: '12. Изменения условий', en: '12. Changes to these terms' },
    p: [
      {
        ru: 'Мы можем обновлять эти условия; о существенных изменениях уведомим в приложении или по email до их вступления в силу. Продолжение использования сервиса после вступления изменений в силу означает согласие с обновлёнными условиями.',
        en: 'We may update these terms; material changes will be announced in the app or by email before they take effect. Continued use of the service after changes take effect constitutes acceptance of the updated terms.',
      },
    ],
  },
  {
    id: 'law',
    h: { ru: '13. Применимое право и оператор', en: '13. Governing law and operator' },
    p: [
      {
        ru: 'Оператор сервиса — Lexab. [Полные реквизиты юридического лица будут указаны до коммерческого запуска.]',
        en: 'The service operator is Lexab. [Full legal-entity details will be provided before commercial launch.]',
      },
      {
        ru: 'Применимое право и порядок разрешения споров будут определены вместе с реквизитами оператора; до этого мы просим направлять любые претензии через контакты, указанные ниже, — мы постараемся разрешить спор путём переговоров.',
        en: 'The governing law and dispute-resolution procedure will be specified together with the operator’s details; until then, please direct any claims via the contacts below — we will seek to resolve disputes through negotiation.',
      },
    ],
  },
  {
    id: 'contacts',
    h: { ru: '14. Контакты', en: '14. Contact' },
    p: [
      {
        ru: 'По вопросам, связанным с этими условиями, напишите нам в Telegram @MANAGER_CIVIS или на privacy@lexai.app.',
        en: 'For questions about these terms, contact us on Telegram @MANAGER_CIVIS or at privacy@lexai.app.',
      },
    ],
  },
];

const PRIVACY: Section[] = [
  {
    id: 'data-we-collect',
    h: { ru: '1. Какие данные мы собираем', en: '1. What data we collect' },
    p: [
      {
        ru: 'Данные аккаунта: имя, email и хэш пароля — пароли хранятся только в виде scrypt-хэша, восстановить исходный пароль из него нельзя. При входе через Google мы получаем от Google имя, email и идентификатор аккаунта; пароль в этом случае у нас не хранится.',
        en: 'Account data: name, email and a password hash — passwords are stored only as a scrypt hash, from which the original password cannot be recovered. If you sign in with Google, we receive your name, email and account identifier from Google; no password is stored with us in that case.',
      },
      {
        ru: 'Контент: загруженные документы, извлечённый из них текст и результаты анализа — находки, оценки риска, ответы ИИ-ассистента и история чатов.',
        en: 'Content: uploaded documents, the text extracted from them and analysis results — findings, risk assessments, AI assistant replies and chat history.',
      },
      {
        ru: 'Служебные данные: счётчики использования лимитов тарифа (ИИ-запросы, документы, хранилище) и сведения о подписке. Настройки интерфейса (язык, тема и подобное) хранятся локально в вашем браузере (localStorage).',
        en: 'Service data: plan-usage counters (AI requests, documents, storage) and subscription details. Interface preferences (language, theme and the like) are stored locally in your browser (localStorage).',
      },
    ],
  },
  {
    id: 'purposes',
    h: { ru: '2. Цели обработки', en: '2. How we use data' },
    p: [
      {
        ru: 'Данные обрабатываются только для работы сервиса: аутентификация и защита аккаунта, анализ ваших документов, ответы ИИ-ассистента, учёт лимитов тарифа, статистика в вашем кабинете и транзакционные уведомления (например, письмо для сброса пароля).',
        en: 'Data is processed only to run the service: authentication and account protection, analysing your documents, AI assistant replies, tracking plan limits, your dashboard statistics and transactional notifications (for example, a password-reset email).',
      },
      {
        ru: 'Мы не продаём данные третьим лицам, не используем их для рекламы и не используем ваши документы для обучения ИИ-моделей.',
        en: 'We do not sell data to third parties, do not use it for advertising and do not use your documents to train AI models.',
      },
    ],
  },
  {
    id: 'storage',
    h: { ru: '3. Где хранятся данные', en: '3. Where data lives' },
    p: [
      {
        ru: 'Записи хранятся в облачной базе данных Supabase (Postgres), файлы документов — в приватном bucket Supabase Storage. Прямого публичного доступа к файлам нет: они выдаются только по временным подписанным ссылкам с ограниченным сроком действия.',
        en: 'Records are stored in a Supabase cloud database (Postgres); document files live in a private Supabase Storage bucket. There is no direct public access to files: they are served only via temporary signed links with a limited lifetime.',
      },
    ],
  },
  {
    id: 'security',
    h: { ru: '4. Безопасность', en: '4. Security' },
    p: [
      {
        ru: 'Данные шифруются при передаче (TLS). Пароли хранятся только в виде scrypt-хэшей. Доступ к данным через публичный API базы закрыт политиками безопасности (Row Level Security), а файлы доступны только по подписанным ссылкам.',
        en: 'Data is encrypted in transit (TLS). Passwords are stored only as scrypt hashes. Public API access to the database is blocked by Row Level Security policies, and files are accessible only via signed links.',
      },
    ],
  },
  {
    id: 'subprocessors',
    h: { ru: '5. Субобработчики', en: '5. Subprocessors' },
    p: [
      {
        ru: 'Для работы сервиса мы используем ограниченный круг надёжных сервисов корпоративного уровня: провайдер ИИ-моделей — анализ документов и ответы ассистента; сервис векторного поиска — подбор релевантных норм по базе текстов законов (в качестве поискового запроса может передаваться фрагмент текста анализируемого документа); почтовый сервис — отправка служебных писем; Google — вход через Google-аккаунт (OAuth); облачная платформа — база данных и файловое хранилище.',
        en: 'We rely on a limited set of trusted, enterprise-grade services to run the platform: an AI model provider — document analysis and assistant replies; a vector-search service — matching relevant provisions across the statutory-text corpus (an excerpt of the document under review may be sent as the search query); an email service — transactional messages; Google — sign-in with a Google account (OAuth); a cloud platform — database and file storage.',
      },
      {
        ru: 'Каждый поставщик получает только те данные, которые необходимы для его функции.',
        en: 'Each provider receives only the data necessary for its function.',
      },
    ],
  },
  {
    id: 'ai-training',
    h: { ru: '6. ИИ и обучение моделей', en: '6. AI and model training' },
    p: [
      {
        ru: 'Текст ваших документов передаётся провайдеру ИИ-моделей только для выполнения анализа. На платных тарифах по условиям использования провайдера данные, переданные через API, не используются для обучения моделей.',
        en: 'The text of your documents is sent to the AI model provider only to perform the analysis. On paid plans, under the provider’s terms, data submitted via the API is not used to train models.',
      },
      {
        ru: 'На бесплатном тарифе запросы к ИИ могут обрабатываться дополнительным сторонним поставщиком ИИ-инфраструктуры, в том числе на серверах за пределами вашей юрисдикции, и по его условиям могут использоваться для улучшения его сервисов. Если для ваших документов это критично, используйте платные тарифы. Актуальный перечень категорий субобработчиков предоставляется по запросу на privacy@lexai.app.',
        en: 'On the Free plan, AI requests may be processed by an additional third-party AI infrastructure provider, including on servers outside your jurisdiction, and under its terms may be used to improve its services. If this matters for your documents, use a paid plan. The current list of subprocessor categories is available on request at privacy@lexai.app.',
      },
      {
        ru: 'Отдельный сервис векторного поиска применяется для индексации базы официальных текстов законов и поиска по ней: при анализе договора фрагмент его текста может передаваться этому сервису как поисковый запрос для подбора релевантных норм. Целые документы туда не загружаются и не хранятся там.',
        en: 'A dedicated vector-search service is used to index the corpus of official statutory texts and to search it: during a contract review, an excerpt of the contract text may be sent to that service as a search query to match relevant provisions. Whole documents are not uploaded to or stored with that service.',
      },
    ],
  },
  {
    id: 'retention',
    h: { ru: '7. Сроки хранения', en: '7. Data retention' },
    p: [
      {
        ru: 'Данные хранятся, пока ваш аккаунт активен. Документы и результаты анализа хранятся до тех пор, пока вы сами их не удалите или не удалите аккаунт целиком.',
        en: 'Data is kept for as long as your account is active. Documents and analyses are kept until you delete them yourself or delete the account entirely.',
      },
    ],
  },
  {
    id: 'deletion',
    h: { ru: '8. Удаление данных', en: '8. Deleting your data' },
    p: [
      {
        ru: 'При удалении документа удаляются его записи в базе данных и файл из хранилища. При удалении аккаунта (Настройки → Безопасность → Удалить аккаунт) удаляются все ваши данные: профиль, документы, результаты анализа, история чатов и файлы из хранилища. Удаление необратимо.',
        en: 'When you delete a document, its database records and the file in storage are removed. When you delete your account (Settings → Security → Delete account), all your data is removed: profile, documents, analyses, chat history and files in storage. Deletion is irreversible.',
      },
    ],
  },
  {
    id: 'rights',
    h: { ru: '9. Ваши права', en: '9. Your rights' },
    p: [
      {
        ru: 'Вы можете получить доступ к своим данным, исправить их, удалить их или запросить экспорт. Профиль редактируется в Настройках, документы выгружаются из кабинета, удаление документа или аккаунта доступно самостоятельно. По запросу на экспорт или иным вопросам о данных напишите на privacy@lexai.app.',
        en: 'You can access your data, correct it, delete it or request an export. The profile is editable in Settings, documents can be downloaded from your workspace, and deletion of a document or the account is available self-service. For export requests or other data questions, write to privacy@lexai.app.',
      },
    ],
  },
  {
    id: 'cookies',
    h: { ru: '10. Cookies и localStorage', en: '10. Cookies and localStorage' },
    p: [
      {
        ru: 'Мы не используем рекламные или сторонние аналитические трекеры. Хранилище браузера (localStorage) используется для настроек интерфейса (язык, тема), поддержания сессии входа, черновиков неотправленных сообщений и служебных пометок (например, статус ознакомительного тура). Эти данные остаются на вашем устройстве и удаляются штатными средствами браузера.',
        en: 'We do not use advertising or third-party analytics trackers. Browser storage (localStorage) is used for interface preferences (language, theme), keeping your sign-in session, drafts of unsent messages and service flags (such as onboarding-tour status). This data stays on your device and can be cleared with standard browser controls.',
      },
    ],
  },
  {
    id: 'children',
    h: { ru: '11. Данные детей', en: '11. Children’s data' },
    p: [
      {
        ru: 'Сервис предназначен для лиц старше 18 лет и не адресован детям. Мы сознательно не собираем данные детей; если вам известно о таком аккаунте, сообщите нам — он будет удалён.',
        en: 'The service is intended for people over 18 and is not directed at children. We do not knowingly collect children’s data; if you become aware of such an account, let us know and it will be deleted.',
      },
    ],
  },
  {
    id: 'policy-changes',
    h: { ru: '12. Изменения политики', en: '12. Changes to this policy' },
    p: [
      {
        ru: 'Мы можем обновлять эту политику; о существенных изменениях уведомим в приложении или по email. Дата последнего обновления указана вверху страницы.',
        en: 'We may update this policy; material changes will be announced in the app or by email. The date of the latest update is shown at the top of the page.',
      },
    ],
  },
  {
    id: 'contact',
    h: { ru: '13. Контакт', en: '13. Contact' },
    p: [
      {
        ru: 'По вопросам обработки данных напишите нам: privacy@lexai.app.',
        en: 'For privacy questions, contact us at privacy@lexai.app.',
      },
    ],
  },
];

/** Static legal page (Terms of Use / Privacy Policy), public — no sign-in needed. */
export function LegalPage({ kind }: { kind: 'terms' | 'privacy' }) {
  const { lang } = useI18n();
  const navigate = useNavigate();
  const location = useLocation();
  /** Return to wherever the reader came from; direct visits land on the home page. */
  const goBack = () => {
    if (location.key !== 'default') navigate(-1);
    else navigate('/');
  };
  const sections = kind === 'terms' ? TERMS : PRIVACY;
  // Юридический текст существует на русском и английском. Пользователям
  // остальных языков честно говорим, какая версия юридически обязательна, —
  // стандартная практика «prevailing language» вместо рискованного машинного
  // перевода правового документа.
  const prevailingNote =
    lang === 'ru' || lang === 'en'
      ? null
      : {
          de: 'Rechtlich verbindlich ist die englische Fassung dieses Dokuments. Diese Seite wird aus praktischen Gründen auf Englisch angezeigt.',
          ar: 'النسخة الإنجليزية من هذه الوثيقة هي النسخة الملزمة قانونيًا. تُعرض هذه الصفحة بالإنجليزية للتيسير.',
          kk: 'Бұл құжаттың заңды күші бар нұсқасы — ағылшын тіліндегі нұсқа. Бет ыңғайлылық үшін ағылшын тілінде көрсетіледі.',
          uz: 'Ushbu hujjatning yuridik kuchga ega matni — inglizcha nusxasi. Sahifa qulaylik uchun ingliz tilida ko‘rsatiladi.',
        }[lang as 'de' | 'ar' | 'kk' | 'uz'];
  const title =
    kind === 'terms'
      ? lang === 'ru'
        ? 'Условия использования'
        : 'Terms of Use'
      : lang === 'ru'
        ? 'Политика конфиденциальности'
        : 'Privacy Policy';
  usePageTitle(title);

  return (
    <div className={styles.legalPage}>
      <main className={styles.legalInner}>
        <div className={styles.legalTop}>
          <Link to="/" className={styles.legalBrand}>
            <Avatar size={30} />
            <span>Lexab</span>
          </Link>
          <button type="button" className={styles.legalBack} onClick={goBack}>
            ← {lang === 'ru' ? 'Назад' : 'Back'}
          </button>
        </div>
        <h1 className={styles.legalTitle}>{title}</h1>
        <p className={styles.legalUpdated}>{lang === 'ru' ? 'Обновлено: июль 2026' : 'Last updated: July 2026'}</p>
        {prevailingNote ? (
          <p
            className={styles.legalP}
            role="note"
            style={{
              padding: '10px 14px',
              borderRadius: 10,
              background: 'color-mix(in srgb, var(--accent) 9%, transparent)',
              border: '1px solid color-mix(in srgb, var(--accent) 25%, transparent)',
            }}
          >
            {prevailingNote}
          </p>
        ) : null}
        <nav aria-label={lang === 'ru' ? 'Содержание' : 'Contents'} style={{ margin: '0 0 10px' }}>
          <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 4 }}>
            {sections.map((s) => (
              <li key={s.id} style={{ fontSize: 13.5, lineHeight: 1.5 }}>
                <a href={`#${s.id}`} className={styles.legalLink} style={{ fontWeight: 500 }}>
                  {pickText(s.h, lang)}
                </a>
              </li>
            ))}
          </ul>
        </nav>
        {sections.map((s) => (
          <section key={s.id} id={s.id} style={{ scrollMarginTop: 24 }}>
            <h2 className={styles.legalH2}>{pickText(s.h, lang)}</h2>
            {s.p.map((p, i) => (
              <p key={i} className={styles.legalP}>
                {pickText(p, lang)}
              </p>
            ))}
          </section>
        ))}
        <p className={styles.legalP} style={{ marginTop: 22 }}>
          <button
            type="button"
            className={styles.legalLink}
            style={{ background: 'none', border: 0, padding: 0, cursor: 'pointer', font: 'inherit' }}
            onClick={goBack}
          >
            ← {lang === 'ru' ? 'Назад' : 'Back'}
          </button>
        </p>
      </main>
    </div>
  );
}
