import { Link } from 'react-router-dom';
import { Avatar } from '@/components/ui/Avatar';
import { useI18n } from '@/i18n/I18nProvider';
import styles from './pages.module.css';

interface Section {
  h: { ru: string; en: string };
  p: { ru: string; en: string }[];
}

const TERMS: Section[] = [
  {
    h: { ru: '1. О сервисе', en: '1. About the service' },
    p: [
      {
        ru: 'LexAI — платформа интеллектуального анализа контрактов: загрузка документов, автоматический поиск рисков, правки, шаблоны и электронные подписи.',
        en: 'LexAI is an AI contract-intelligence platform: document upload, automated risk review, redlines, templates and e-signatures.',
      },
    ],
  },
  {
    h: { ru: '2. Не является юридической консультацией', en: '2. Not legal advice' },
    p: [
      {
        ru: 'Результаты анализа формируются искусственным интеллектом и носят информационный характер. Они не заменяют консультацию квалифицированного юриста. Ответственность за принятые решения несёт пользователь.',
        en: 'Analysis output is generated by AI and is informational only. It does not replace advice from a qualified lawyer. Decisions taken remain the user’s responsibility.',
      },
    ],
  },
  {
    h: { ru: '3. Аккаунт и доступ', en: '3. Account and access' },
    p: [
      {
        ru: 'Вы отвечаете за сохранность своих учётных данных. Запрещено использовать сервис для незаконных целей, нарушения прав третьих лиц или попыток получить несанкционированный доступ.',
        en: 'You are responsible for keeping your credentials safe. Using the service for unlawful purposes, infringing third-party rights, or attempting unauthorised access is prohibited.',
      },
    ],
  },
  {
    h: { ru: '4. Тарифы и лимиты', en: '4. Plans and limits' },
    p: [
      {
        ru: 'Объём доступных функций (AI-запросы, документы, хранилище) определяется выбранным тарифом. Актуальные лимиты указаны на странице «Тарифы» и в Настройках.',
        en: 'Available usage (AI requests, documents, storage) is defined by your plan. Current limits are shown on the Plans page and in Settings.',
      },
    ],
  },
  {
    h: { ru: '5. Изменения условий', en: '5. Changes' },
    p: [
      {
        ru: 'Мы можем обновлять эти условия; о существенных изменениях уведомим в приложении. Продолжение использования сервиса означает согласие с обновлёнными условиями.',
        en: 'We may update these terms; material changes will be announced in the app. Continued use of the service constitutes acceptance of the updated terms.',
      },
    ],
  },
];

const PRIVACY: Section[] = [
  {
    h: { ru: '1. Какие данные мы храним', en: '1. What we store' },
    p: [
      {
        ru: 'Профиль (имя, email, организация), загруженные документы и результаты их анализа, историю чатов, данные о подписке и использовании лимитов.',
        en: 'Your profile (name, email, organisation), uploaded documents and their analyses, chat history, subscription and usage data.',
      },
    ],
  },
  {
    h: { ru: '2. Как мы их используем', en: '2. How we use it' },
    p: [
      {
        ru: 'Только для работы сервиса: анализ ваших документов, ответы ИИ, статистика в вашем кабинете. Мы не продаём данные третьим лицам и не используем ваши документы для обучения моделей.',
        en: 'Only to run the service: analysing your documents, AI replies, and your dashboard statistics. We do not sell data to third parties and do not use your documents to train models.',
      },
    ],
  },
  {
    h: { ru: '3. Где хранятся данные', en: '3. Where data lives' },
    p: [
      {
        ru: 'Данные хранятся в облачной базе данных и защищённом файловом хранилище с шифрованием при передаче. Доступ к данным через публичный API закрыт политиками безопасности (RLS).',
        en: 'Data is stored in a managed cloud database and private file storage, encrypted in transit. Public API access to the data is blocked by Row Level Security policies.',
      },
    ],
  },
  {
    h: { ru: '4. Ваши права', en: '4. Your rights' },
    p: [
      {
        ru: 'Вы можете выгрузить свои документы, изменить данные профиля или полностью удалить аккаунт со всеми данными (Настройки → Безопасность → Удалить аккаунт). Удаление необратимо.',
        en: 'You can export your documents, edit your profile, or permanently delete your account with all data (Settings → Security → Delete account). Deletion is irreversible.',
      },
    ],
  },
  {
    h: { ru: '5. Вопросы', en: '5. Contact' },
    p: [
      {
        ru: 'По вопросам обработки данных напишите нам: privacy@lexai.app.',
        en: 'For privacy questions, contact us at privacy@lexai.app.',
      },
    ],
  },
];

/** Static legal page (Terms of Use / Privacy Policy), public — no sign-in needed. */
export function LegalPage({ kind }: { kind: 'terms' | 'privacy' }) {
  const { lang } = useI18n();
  const sections = kind === 'terms' ? TERMS : PRIVACY;
  const title =
    kind === 'terms'
      ? lang === 'ru'
        ? 'Условия использования'
        : 'Terms of Use'
      : lang === 'ru'
        ? 'Политика конфиденциальности'
        : 'Privacy Policy';

  return (
    <div className={styles.legalPage}>
      <div className={styles.legalInner}>
        <Link to="/login" className={styles.legalBrand}>
          <Avatar size={30} />
          <span>LexAI</span>
        </Link>
        <h1 className={styles.legalTitle}>{title}</h1>
        <p className={styles.legalUpdated}>{lang === 'ru' ? 'Обновлено: июль 2026' : 'Last updated: July 2026'}</p>
        {sections.map((s) => (
          <section key={s.h.en}>
            <h2 className={styles.legalH2}>{s.h[lang]}</h2>
            {s.p.map((p, i) => (
              <p key={i} className={styles.legalP}>
                {p[lang]}
              </p>
            ))}
          </section>
        ))}
        <p className={styles.legalP}>
          <Link to="/login" className={styles.legalLink}>
            ← {lang === 'ru' ? 'Вернуться ко входу' : 'Back to sign in'}
          </Link>
        </p>
      </div>
    </div>
  );
}
