/** Barrel export for the API layer. Import from `@/api` everywhere in the UI. */
export { analysisApi } from './analysis.api';
export { analyticsApi, versionsApi, userApi } from './analytics.api';
export { chatsApi } from './chats.api';
export { documentsApi } from './documents.api';
export type { DocumentQuery } from './documents.api';
export { projectsApi, PENDING_PROJECT_KEY, setPendingProject, consumePendingProject, clearPendingProject } from './projects.api';
export { signaturesApi } from './signatures.api';
export type { SendSignatureInput } from './signatures.api';
export { billingApi } from './billing.api';
export type { PlanLimits, UsageMetric } from './billing.api';
export { teamApi, ROLE_COLORS } from './team.api';
export type { TeamMember, TeamInvitation, TeamRole } from './team.api';
export { templatesApi } from './templates.api';
export { playbooksApi } from './playbooks.api';
export type { CreatePlaybookInput, UpdatePlaybookInput } from './playbooks.api';
export { contractsApi } from './contracts.api';
export { batchApi } from './batch.api';
export { workflowsApi } from './workflows.api';
export { apiKeysApi } from './apiKeys.api';
export type { ApiKeyInfo, ApiKeyCreated, ApiUsage } from './apiKeys.api';
export { securityApi } from './security.api';
export type { TwoFactorStatus, TwoFactorSetup, SessionInfo, AccessReviewRow } from './security.api';
export { ttsApi } from './tts.api';
export { promptsApi } from './prompts.api';
export { ApiError } from './util';
export { USE_MOCK } from './client';
